import { LoadoutConfig } from "./types";

const filepath = "loadouts\\42.loadout";
const isFromWindows = true;

export const FUNNY_LOADOUTS: LoadoutConfig[] = [
  {
    name: "WEEEEEE!",
    primary: 43,
    secondary: 42,
    equipment: 61,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Survival proof",
    primary: 37,
    secondary: 50,
    equipment: 67,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Friendly neighbour",
    primary: 24,
    secondary: 24,
    equipment: 67,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "One shot is all it takes",
    primary: 26,
    secondary: 26,
    equipment: 70,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Never gets old", // https://www.youtube.com/watch?v=nibNfob0YZs
    primary: 0,
    secondary: 0,
    equipment: 76,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "THE best",
    primary: 16,
    secondary: 51,
    equipment: 61,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Broken wrists",
    primary: 8,
    secondary: 8,
    equipment: 78,
    isDualWield: true,
    filepath,
    isFromWindows,
  },
  {
    name: "Ya don't move",
    primary: 1,
    secondary: 1,
    equipment: 78,
    isDualWield: true,
    filepath,
    isFromWindows,
  },
  {
    name: "Welcome boss",
    primary: 0,
    secondary: 0,
    equipment: 79,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Nice surprise",
    primary: 30,
    secondary: 34,
    equipment: 74,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "Kaboom!",
    primary: 51,
    secondary: 1,
    equipment: 72,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
  {
    name: "360 NO SCOPE!",
    primary: 32,
    secondary: 42,
    equipment: 70,
    isDualWield: false,
    filepath,
    isFromWindows,
  },
];
